#main pipeline
name: end to end pipline with security

on: 
    push: 
        
jobs: 
    code-qualiy: 
        uses: ./.github/workflows/code-quality.yml       
        
    git-leaks:
        uses: ./.github/workflows/git-leaks.yml    
          

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml